// Generated by delombok at Tue Sep 03 16:32:39 EDT 2019
package com.gpch.login.model;

import javax.persistence.*;

@Entity
@Table(name = "role")
public class Role {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "role_id")
    private int id;
    @Column(name = "role")
    private String role;


    @java.lang.SuppressWarnings("all")
    public static class RoleBuilder {
        @java.lang.SuppressWarnings("all")
        private int id;
        @java.lang.SuppressWarnings("all")
        private String role;

        @java.lang.SuppressWarnings("all")
        RoleBuilder() {
        }

        @java.lang.SuppressWarnings("all")
        public RoleBuilder id(final int id) {
            this.id = id;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public RoleBuilder role(final String role) {
            this.role = role;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public Role build() {
            return new Role(id, role);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "Role.RoleBuilder(id=" + this.id + ", role=" + this.role + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static RoleBuilder builder() {
        return new RoleBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public int getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getRole() {
        return this.role;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final int id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setRole(final String role) {
        this.role = role;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Role)) return false;
        final Role other = (Role) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getId() != other.getId()) return false;
        final java.lang.Object this$role = this.getRole();
        final java.lang.Object other$role = other.getRole();
        if (this$role == null ? other$role != null : !this$role.equals(other$role)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Role;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getId();
        final java.lang.Object $role = this.getRole();
        result = result * PRIME + ($role == null ? 43 : $role.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Role(id=" + this.getId() + ", role=" + this.getRole() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public Role(final int id, final String role) {
        this.id = id;
        this.role = role;
    }

    @java.lang.SuppressWarnings("all")
    public Role() {
    }
}
